/*
 * internal_flash.h
 *
 *  Created on: 17 באפר׳ 2018
 *      Author: oferf
 */

#ifndef INTERNAL_FLASH_H_
#define INTERNAL_FLASH_H_

#include "main.h"


//Flash Pasge 97 in refrence manual 1MByte 512 pages of 2K flash

typedef enum
{
	BOOTLOADER_STARTING_ADDRESS 	 = ADDR_FLASH_PAGE_0,   // page 0
	BOOTLOADER_STOPPING_ADDRESS 	 = ADDR_FLASH_PAGE_10,  // page 10
	APPLICATION_STARTING_ADDRESS	 = ADDR_FLASH_PAGE_11,  // page 11
	APPLICATION_STOPPING_ADDRESS	 = ADDR_FLASH_PAGE_135, // page 135
	VERSION_A_STARTING_ADDRESS  	 = ADDR_FLASH_PAGE_136, // page 136
	VERSION_A_STOPPING_ADDRESS  	 = ADDR_FLASH_PAGE_260, // page 260
	VERSION_B_STARTING_ADDRESS  	 = ADDR_FLASH_PAGE_261, // page 261
	VERSION_B_STOPPING_ADDRESS  	 = ADDR_FLASH_PAGE_385, // page 385
	DEFAULT_VERSION_STARTING_ADDRESS = ADDR_FLASH_PAGE_386, // page 386
	DEFAULT_VERSION_STOPPING_ADDRESS = ADDR_FLASH_PAGE_510, // page 510
	EEPROM_IMAGE_STARTING_ADDRESS	 = ADDR_FLASH_PAGE_511  // page 511
} FLASH_ADDRESS;

typedef enum
{
	BOOTLOADER_FIRST_PAGE      = 0,
	BOOTLOADER_LAST_PAGE       = 10,
	APPLICATION_FIRST_PAGE     = 11,
	APPLICATION_LAST_PAGE      = 135,
	VERSION_A_FIRST_PAGE       = 136,
	VERSION_A_LAST_PAGE        = 260,
	VERSION_B_FIRST_PAGE       = 261,
	VERSION_B_LAST_PAGE        = 385,
	DEFAULT_VERSION_FIRST_PAGE = 386,
	DEFAULT_VERSION_LAST_PAGE  = 510,
	EEPROM_IMAGE_PAGE	       = 511
} PAGE_NUMBER;

#endif /* INTERNAL_FLASH_H_ */
